version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./Visualizer:/srv/visualizer/Visualizer
    depends_on:
      - db
