version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/srv/visualizer
    depends_on:
      - db
