# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.DateField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
