# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
